# Set update schedule for GitHub Actions

version: 2
updates:
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
  - package-ecosystem: 'go'
    directory: '/'
    schedule:
      interval: 'daily'

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
